#include<Windows.h>
/*
	system merrics display structure
*/
#define NUMLINES     ((int)(sizeof sysmetrics/sizeof sysmetrics[0]))
struct
{
	int iIndex;
	TCHAR *szLabel;
	TCHAR *szDesc;
}sysmetrics[] =
{
	SM_CXSCREEN,					TEXT("SM_CXSCREEN"),				TEXT("屏幕宽度in pixels"),
	SM_CYSCREEN,					TEXT("SM_CYSCREEN"),				TEXT("屏幕高度in pixels"),
	SM_CXVSCROLL,				TEXT("SM_CXVSCROLL"),			TEXT("垂直滑块宽度"),
	SM_CYHSCROLL,				TEXT("SM_CYHSCROLL"),			TEXT("水平滑块高度"),
	SM_CYCAPTION,				TEXT("SM_CYCAPTION"),			TEXT("标题栏高度"),
	SM_CXBORDER,				TEXT("SM_CXBORDER"),			TEXT("窗口边框宽度"),
	SM_CYBORDER	,				TEXT("SM_CYBORDER"),			TEXT("窗口边框高度"),
	SM_CXFIXEDFRAME,			TEXT("SM_CXFIXEDFRAME"),		TEXT("对话框窗口宽度"),
	SM_CYFIXEDFRAME,			TEXT("SM_CYDIXEDFRAME"),	TEXT("对话框窗口高度"),
	SM_CYVTHUMB,				TEXT("SM_CYVTHUMB"),			TEXT("垂直 滑块thumb高度"),
	SM_CXHTHUMB,				TEXT("SM_CXHTHUMB"),			TEXT("水平滑块thumb宽度"),
	SM_CXICON,						TEXT("SM_CXICON"),			    TEXT("图标宽度"),
	SM_CYICON,						TEXT("SM_CYICON"),				TEXT("图标高度"),
	SM_CXCURSOR,				TEXT("SM_CXCURSOR"),			TEXT("光标宽度"),
	SM_CYCURSOR,				TEXT("SM_CYCURSOR"),			TEXT("光标高度"),
	SM_CYMENU,					TEXT("SM_CYMENU"),				TEXT("菜单栏高度"),
	SM_CXFULLSCREEN,			TEXT("SM_CXFULLSCREEN"),	    TEXT("全屏客户区宽度"),
	SM_CYFULLSCREEN,			TEXT("SM_CYFULLSCREEN"),		TEXT("全屏客户区高度"),
	SM_CYKANJIWINDOW,		TEXT("SM_KANJIWINDOW"),		TEXT("kanji 窗口高度"),
	SM_MOUSEPRESENT,		TEXT("SM_MOUSEPRESENT"),	TEXT("mouse present flag"),
	SM_CYVSCROLL,				TEXT("SM_CYVSCROLL"),			TEXT("水平滑块箭头高度"),
	SM_CXHSCROLL,				TEXT("SM_CXHSCROLL"),			TEXT("水平滑块箭头宽度"),
	SM_DEBUG,						TEXT("SM_DEBUG"),					TEXT("debug version flag"),
	SM_SWAPBUTTON,			TEXT("SM_SWAPBUTTON"),		TEXT("mouse buttons swapped flag"),
	SM_CXMIN,						TEXT("SM_CXMIN"),					TEXT("窗口最小宽度"),
	SM_CYMIN,						TEXT("SM_CYMIN"),					TEXT("窗口最小高度"),
	SM_CXSIZE,						TEXT("SM_CXSIZE"),					TEXT("Min/Max/Close button 宽度"),
	SM_CYSIZE,						TEXT("SM_CYSIZE"),					TEXT("Min/Max/Close button 高度"),
	SM_CXSIZEFRAME,			TEXT("SM_CXSIZEFRAME"),		TEXT("windows sizing frame width"),
	SM_CYSIZEFRAME,			TEXT("SM_CYSIZEFRAME"),		TEXT("windows sizing frame hight"),
	SM_CXMINTRACK,			TEXT("SM_CXMINTRACK"),		TEXT("MiniMum window tracking width"),
	SM_CYMINTRACK,			TEXT("SM_CYMINTRACK"),		TEXT("MiniMum window tracking higth"),
	SM_CXDOUBLECLK,			TEXT("SM_CXDOUBLECLK"),		TEXT("double click x tolerance"),
	SM_CYDOUBLECLK,			TEXT("SM_CYDOUBLECLK"),		TEXT("double click y tolerance"),
	SM_CXICONSPACING,		TEXT("SM_CXICONSPACING"),	TEXT("水平图标间隔"),
	SM_CYICONSPACING,		TEXT("SM_CYICONSPACING"),	TEXT("垂直图标间隔"),
	SM_MENUDROPALIGNMENT,TEXT("SM_MENUDROPALIGNMENT"),TEXT("LEFT OR RIGHT MENU DROP"),
	SM_PENWINDOWS,			TEXT("SM_PENWINDOWS"),		TEXT("Pen extension installed"),
	SM_DBCSENABLED,			TEXT("SM_DBCSENABLED"),		TEXT("Double-byte Char set enabled"),
	SM_CMOUSEBUTTONS,	TEXT("SM_CMOUSEBUTTONS"),TEXT("Numbers of mouse buttons"),
	SM_SECURE,						TEXT("SM_SECURE"),					TEXT("Security present flag"),
	SM_CXEDGE,					TEXT("SM_CXEDGE"),				TEXT("3-D BORDER WIDTH"),
	SM_CYEDGE,						TEXT("SM_CYEDGE"),				TEXT("3-D BORDER HIGHT"),
	SM_CXMINSPACING,		TEXT("SM_CXMINSPACING"),	TEXT("Minisized window spacing width"),
	SM_CYMINSPACING,		TEXT("SM_CYMINSPACING"),	TEXT("Minisized window spacing hight"),
	SM_CXSMICON,				TEXT("SM_CXSMICON"),			TEXT("small icon width"),
	SM_CYSMICON,				TEXT("SM_CYSMICON"),			TEXT("small icon hight"),
	SM_CYSMCAPTION,			TEXT("SM_CYSMCAPTION"),		TEXT("SMALL CAPTION HIGHT"),
	SM_CXSMSIZE,					TEXT("SM_CXSMSIZE"),				TEXT("small caption button width"),
	SM_CYSMSIZE,					TEXT("SM_CYSMSIZE"),				TEXT("small caption button hight"),
	SM_CXMENUSIZE,				TEXT("SM_CXMENUSIZE"),			TEXT("MENU BAR BUTTON WIDTH"),
	SM_CYMENUSIZE,				TEXT("SM_CXMENUSIZE"),			TEXT("MENU BAR BUTTON HIGHT"),
	SM_ARRANGE,					TEXT("SM_ARRANGE"),				TEXT("HOW MINIMIZED WINDOWS ARRANGED"),
	SM_CXMINIMIZED,			TEXT("SM_CXMINIMIZED"),		TEXT("Minimized window width"),
	SM_CYMINIMIZED,			TEXT("SM_CYMINIMIZED"),		TEXT("Minimized window hight"),
	SM_CXMAXTRACK,			TEXT("SM_CXMAXTRACK"),		TEXT("Maximum draggable width"),
	SM_CYMAXTRACK,			TEXT("SM_CYMAXTRACK"),		TEXT("Maximum draggable hight"),
	SM_CXMAXIMIZED,			TEXT("SM_CXMAXIMIZED"),		TEXT("width of maximized window"),
	SM_CYMAXIMIZED,			TEXT("SM_CYMAXIMIZED"),		TEXT("hight of maximized window"),
	SM_NETWORK,					TEXT("SM_NETWORK"),				TEXT("Network present flag"),
	SM_CLEANBOOT,				TEXT("SM_CLEANBOOT"),			TEXT("how system was booted"),
	SM_CXDRAG,					TEXT("SM_CXDRAG"),				TEXT("Avoid drag x tolerance"),
	SM_CYDRAG,					TEXT("SM_CYDRAG"),				TEXT("Avoid drag x tolerance"),
	SM_SHOWSOUNDS,			TEXT("SM_SHOWSOUNDS"),		TEXT("Present sounds visually"),
	SM_CXMENUCHECK,		TEXT("SM_CXMENUCHECK"),	TEXT("Menu check-mark width"),
	SM_CYMENUCHECK,			TEXT("SM_CYMENUCHECK"),	TEXT("Menu check-mark hight"),
	SM_SLOWMACHINE,		TEXT("SM_SLOWMACHINE"),	TEXT("Slow Processor Flag"),
	SM_MIDEASTENABLED,	    TEXT("SM_MIDEASTENABLED"),TEXT("Hebrew and Arabic enabled flag"),
	SM_MOUSEWHEELPRESENT,TEXT("SM_MOUSEWHEELPRESENT"),TEXT("Mouse wheel present flag"),
	SM_XVIRTUALSCREEN,		TEXT("SM_XVIRTUALSCREEN"),	TEXT("Virtual screen x origin"),
	SM_YVIRTUALSCREEN,		TEXT("SM_YVIRTUALSCREEN"),	TEXT("virtual screen y origin"),
	SM_CXVIRTUALSCREEN,	TEXT("SM_CXVIRTUALSCREEN"),TEXT("Virtual screen width"),
	SM_CYVIRTUALSCREEN,	TEXT("SM_CYVIRTUALSCREEN"),TEXT("Virtual screen hight"),
	SM_CMONITORS,				TEXT("SM_CMONITORS"),			TEXT("numbers of monitors"),
	SM_SAMEDISPLAYFORMAT,TEXT("SM_SAMEDISPLAYFORMAT"),TEXT("same color format flag")
};
